apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname
  namespace: ntk
spec:
  provider: azure
  secretObjects:
    - secretName: database-configs
      type: Opaque
      data:
        - objectName: DatabaseConnectionString
          key: DatabaseConnectionString
        - objectName: ApiKey
          key: ApiKey
        - objectName: StorageConnectionString
          key: StorageConnectionString  
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    keyvaultName: "kv-ntk"
    objects: |
      array:
        - |
          objectName: ApiKey
          objectType: secret
          objectVersion: ""
        - |
          objectName: DatabaseConnectionString
          objectType: secret
          objectVersion: ""
        - |
          objectName: StorageConnectionString
          objectType: secret
          objectVersion: ""
    tenantID: "YOURTENANTID"