### check health of the asp.net core 
GET {{api-url}}/health
Accept: application/json

### check health of the API
GET {{api-url}}/lg/health
Accept: application/json

### get link group 
GET {{api-url}}/lg/get-all
Accept: application/json
X-Api-Key: {{api-key}}

### get links from specific group
@linkGroupId = ""
GET {{api-url}}/lg/get-links?linkGroupId={{linkGroupId}}}
Accept: application/json
X-Api-Key: {{api-key}}
