### check health of the init api
GET {{init-url}}/health

### generate db
POST {{init-url}}/init/db
X-Api-Key: {{api-key}}

### generate tables
POST {{init-url}}/init/tables
X-Api-Key: {{api-key}}

### get check if app is working and sql connection is established
GET {{init-url}}/generate/check

### generate categories
POST {{init-url}}/generate/categories
X-Api-Key: {{api-key}}

### generate users
POST {{init-url}}/generate/users
X-Api-Key: {{api-key}}

### generate link groups
POST {{init-url}}/generate/link-groups
X-Api-Key: {{api-key}}

### generate links
POST {{init-url}}/generate/links
X-Api-Key: {{api-key}}



